runtime: nodejs20
service: backend

env_variables:
  NODE_ENV: production
  PORT: 8080
  OPENSEARCH_URL: "http://34.67.27.172:9200"
  GCS_BUCKET: "opensearch-documents-opensearch-doc-search"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always 
